### ISSUE TITLE
PayPal-Mock-Response header results in NullPointerException on response deserialization

### ISSUE THREAD

**Issue by pmiklos** [paypal/Checkout-Java-SDK#31]
I am trying to simulate error responses using the Orders API but setting `PayPal-Mock-Response` request header to `{"mock_application_codes": "COMPLIANCE_VIOLATION"}` for example results in HTTP 404 and the response serialization fails with NPE:

```
java.lang.NullPointerException: null
	at com.paypal.http.Encoder.deserializeResponse(Encoder.java:68)
	at com.paypal.http.HttpClient.parseResponse(HttpClient.java:199)
	at com.paypal.http.HttpClient.execute(HttpClient.java:98)
```

Debugging the code the URL is `https://api.sandbox.paypal.com/v2/checkout/orders?`

An example Paypal debug id is `48f4cc2262224`.

**Comment by Nicooo2201** [comment]
Hi @pmiklos,

I think, I solved this issue. In the following lines I will explain my personal issue and my workaround for it.

**My personal issue with the Checkout Java SDK**:
Every time when I tried to create an order with an simulated error like `AMOUNT_MISMATCH`, I got a NPE like you. While debugging I saw, that the SDK will fetch the access token either from the REST API or from their own cache implementation (in this case from a concurrent hash map). If the access token will comes from the REST API, then I'm running into an error, because I added the `PayPal-Mock-Response` header to the [order create request](https://developer.paypal.com/docs/api/orders/v2/#orders_create). I guess, that PayPal has a internal problem with this header in a access token request. However, there is a really simple workaround.

**My workaround for the above described issue**:
I created a new class which implements PayPal's `Injector` interface, so I override its method `inject(HttpRequest request)`. In this method I've built an simple `if` condition which checks, if the returned value from `request.responseClass()` is equivalent to `AccessToken.class`. In case of `true`, I'm done, i.e make a return in this method, but if the response class is not equivalent to `AccessToken.class`, then I add the `PayPal-Mock-Response` header to the request to simulate an error during a order create request. After that, I added the injector to the `PayPalHttpClient` and execute a order create request with an simulated error without running into an error.

Please note, that you cannot use every error code for the individual requests. Some error codes may return despite the workaround an error (e.g NPE).

I hope, I could help you.
Best regards.

**Comment by tiffanyrzhou** [comment]
Hi @Nicooo2201 , I was able to take a closer look at the issue you were experiencing. 
The workaround solution would work. But I believe the problem is adding the "PayPal-Mock-Response" header in the general [PayPalHttpClient](https://github.com/paypal/Checkout-Java-SDK/blob/develop/checkout-sdk/src/main/java/com/paypal/core/PayPalHttpClient.java) object. This object is used and share across the different endpoints.  And in the case of retrieving an access token, the endpoint doesn't accept PayPal-Mock-Response. 

I would suggest adding such header in the CreateOrderRequest object, this way we can ensure that this header is only being used when for create order endpoint/ or any specific request.
`request.header("PayPal-Mock-Response","{\"mock_application_codes\": `\"AMOUNT_MISMATCH\"}");`
should ideally go here https://github.com/paypal/Checkout-Java-SDK/blob/develop/checkout-sdk-sample/src/main/java/com/paypal/CaptureIntentExamples/CreateOrder.java#L80

**Comment by tiffanyrzhou** [comment]
Hi @pmiklos. You would get a 404 error if the mock_application_codes supplied doesn't apply to that endpoint. The error code `"mock_application_codes": "COMPLIANCE_VIOLATION"` doesn't apply to the create order request, rather the capture order request.  An example would be to add it  the the [captureOrder](https://github.com/paypal/Checkout-Java-SDK/blob/97104aec2ef9bde4b8a0e6bfa3dd31e2b01c5999/checkout-sdk-sample/src/main/java/com/paypal/CaptureIntentExamples/CaptureOrder.java#L33) method  of the samples.
